# Generated by Django 5.1.1 on 2024-11-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile/default_profile.jpg', upload_to='profile'),
        ),
    ]
